### ISSUE TITLE
request('neverbounce') fails

### ISSUE THREAD

**Issue by nricardo** [NeverBounce/NeverBounceApi-NodeJS#6]
After installation:
```bash
npm install neverbounce --save
```
the module can't be found by node when simply require it:
```javascript
const NeverBounce = require('neverbounce');
```
It seams that npm package is pointing to 'lib/NeverBounce.js' which is not present!! Possibly a missing build before publishing...

To workaround this issue, I needed to do:
```javascript
const NeverBounce = require('../node_modules/neverbounce/src/NeverBounce');
```
`v3` doesn't have this issue.

Error log:
```
Uncaught error in Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: { Error: Cannot find module 'neverbounce'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\cap\hpivaluation\controllers\email.js:16:21)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at handler (D:\cap\hpivaluation\node_modules\express-enrouten\lib\directory.js:79:20)
    at traverse (D:\cap\hpivaluation\node_modules\express-enrouten\lib\directory.js:39:9)
    at D:\cap\hpivaluation\node_modules\express-enrouten\lib\directory.js:34:13
    at Array.forEach (<anonymous>) code: 'MODULE_NOT_FOUND' },
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined } { Error: Cannot find module 'neverbounce'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\cap\hpivaluation\controllers\email.js:16:21)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at handler (D:\cap\hpivaluation\node_modules\express-enrouten\lib\directory.js:79:20)
    at traverse (D:\cap\hpivaluation\node_modules\express-enrouten\lib\directory.js:39:9)
    at D:\cap\hpivaluation\node_modules\express-enrouten\lib\directory.js:34:13
    at Array.forEach (<anonymous>) code: 'MODULE_NOT_FOUND' }

```

**Comment by lukasnagl** [comment]
@nricardo I just encountered the same issue a few minutes ago. My PR #7 fixes this.

Feel free to test it by installing from the fork’s git repository:

```sh
npm install git+https://github.com/j4zz/NeverBounceApi-NodeJS.git
```

**Comment by nricardo** [comment]
@j4zz I saw your fix. Thanks for the update.
I would prefer to keep the lib/, because you shouldn't package your src code to be published on npm. Only the compiled library. I think the there's missing a compile step using webpack or other build tool to make this correction.

**Comment by lukasnagl** [comment]
@nricardo I agree, #7 is just a quickfix until a full build step is added. Personally, I’ll just use axios and hit the REST API for now.

**Comment by mmollick** [comment]
Hey guys, thanks for bring this to our attention. When rewriting the library for our V4 API we decided to drop support for NodeJS versions that are at their EOL. This also meant it was no longer necessary to have a build step as the syntax natively works with NodeJS v4 and newer. Unfortunately, it looks like we neglected to update the main path within the package file.

Thanks for the PR @j4zz, I'll push the update out over NPM shortly.

**Comment by mmollick** [comment]
I've pushed `v4.1.3` to NPM, it includes:
- Patch for package.json courtesy of #7 
- Removal of Babel dev-dependency previously used by Eslint (artifact from the previous version of this library) courtesy of #8

**Comment by nricardo** [comment]
@mmollick Thanks for the update on npm.

Regarding the `main` property:
For that purpose there was a lot of discussion (that still I'm trying to figure out...) on [JSForum](https://github.com/jsforum/jsforum/issues/5) for a fix on that..., but I still prefer to have my modules transpiled, since then I'm always on the safe side.
Other article: [main, jsnext:main and module](https://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/)

Also, if you want to keep as it is, you should add the `engines` property, to define what nodeJS version is supported by the module. For example, take a look at [MomentJS ](http://momentjs.com)[package.json](https://github.com/moment/moment/blob/develop/package.json)

There's also something that would be useful: exposing the response codes for 'valid', 'invalid', etc... so that we do not have to hardcode those values on our own code... That's bad practice!

So my suggestion: export all modules that can/would be useful to who will consume your module.
This way I could simple use the ones already defined in [VerificationObject.js](https://github.com/NeverBounce/NeverBounceApi-NodeJS/blob/master/src/VerificationObject.js).

If you need any PR's on this I would gladly help.

**Comment by mmollick** [comment]
Thanks for the links @nricardo!

Given that this library is only intended to be used on the server I don't see much benefit introducing a build step to transpile the ES6 -> ES2015. I'll add in the `engine` field to the property to properly target the supported NodeJS versions (>=4).

As for the helpers in the `VerificationObject`, we can absolutely expose those in the module. That was the original intention but it looks like we neglected to actually expose them. I'll go ahead and patch this as well.

**Comment by mmollick** [comment]
The engine field and accessible constants have been added to v4.1.4

**Comment by nricardo** [comment]
Thanks a lot for that.
Updated and working as a charm! 👍
